name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Download zig
        shell: bash
        env:
          ZIG_URL: ${{ vars.ZIG_URL }}
        run: |
          wget -q $ZIG_URL
          tar -xf zig*.tar.xz
          mv $(find . -maxdepth 1 -type d -name "zig*") zig
          sudo ln -s $PWD/zig/zig /usr/bin/zig
      - name: Download MacOSX.sdk
        shell: bash
        env:
          MACOS_SDK_URL: ${{ secrets.MACOS_SDK_URL }}
        run: |
          wget -q $MACOS_SDK_URL
          tar -xf *.sdk.tar.xz
          mv $(find . -maxdepth 1 -type d -name "MacOSX*") MacOSX.sdk
      - name: Install zigbuild
        run: |
          cargo install cargo-zigbuild
      - name: Install other env
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update -y
          sudo apt install -y build-essential
          sudo apt install -y gcc-multilib
      - name: Build
        run: |
          export ZIG_HOME=$PWD/zig
          export MACOS_SDK=$PWD/MacOSX.sdk
          bash build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fast-connect
          path: |
            dist/*
            build.log